In [2]:
# pytorch 深度学习框架
# tensor 张量 pytorch中装载数据的基本单位 数据存储单元 就像np.ndarray
#

import torch
data = torch.tensor([[1,2],[3,4]])
data

tensor([[1, 2],
        [3, 4]])

In [3]:
import numpy as np
np_array = np.array([[1,2],[3,4]])
data2 = torch.from_numpy(np_array)
data2       

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [6]:
#添加张量的方式
#torch.tensor()
#torch.from_numpy()
#torch.ones_like(data,dtype = torch.float32)
data3 = torch.ones_like(data2,dtype = torch.int32)
data3
#shape 默认dtype =  folat
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor  = torch.ones(shape)

rand_tensor
ones_tensor
zeros_tensor

# torch.rand() 均匀分布
# torch.randn() 标准正态分布
# torch.normal(mean,std,shape) 一般正态分布
# torch.linspace(start,end,steps) 等差数列

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
#tenssor 属性
tensor = torch.randn(2,2)
print(tensor.shape)
print(tensor.size())
print(tensor.dtype)
print(tensor.device)

torch.Size([2, 2])
torch.Size([2, 2])
torch.float32
cpu


In [9]:
#切换tensor运行 模型训练设备
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor = tensor.to(device)

print(torch.cuda.is_available())
print(tensor)

False
tensor([[ 0.2781, -2.6395],
        [ 1.8954,  1.3800]])


In [16]:
#取tensor 切片
tensor = torch.rand(4,4)

print("first row:",tensor[0,])
print("first column:",tensor[:,0])
print("last column of all dimension:",tensor[...,0])

# tensor 特定位置数值替换
tensor[:,1] = 1
print(tensor)
print(tensor.dtype)
# tensor 改变形状
print(tensor.reshape(4,2,2))

first row: tensor([0.3707, 0.0786, 0.2794, 0.6850])
first column: tensor([0.3707, 0.0849, 0.9652, 0.1202])
last column of all dimension: tensor([0.3707, 0.0849, 0.9652, 0.1202])
tensor([[3.7067e-01, 1.0000e+00, 2.7942e-01, 6.8504e-01],
        [8.4873e-02, 1.0000e+00, 1.4216e-01, 8.1704e-02],
        [9.6516e-01, 1.0000e+00, 6.4281e-01, 7.2506e-01],
        [1.2020e-01, 1.0000e+00, 7.2151e-04, 6.8370e-01]])
torch.float32
tensor([[[3.7067e-01, 1.0000e+00],
         [2.7942e-01, 6.8504e-01]],

        [[8.4873e-02, 1.0000e+00],
         [1.4216e-01, 8.1704e-02]],

        [[9.6516e-01, 1.0000e+00],
         [6.4281e-01, 7.2506e-01]],

        [[1.2020e-01, 1.0000e+00],
         [7.2151e-04, 6.8370e-01]]])


In [26]:
#张量拼接 用列表[]包起来 torch.cat()被拼的维度相同可拼 torch.stack()所有维度相同可拼
tensor = torch.ones(2,2)
tensor1 = torch.cat([tensor,tensor],dim = 0)
print(tensor1,tensor1.dtype,tensor1.shape)
#
tensor2 =torch.cat([tensor,tensor1],dim= 0)
print(tensor2,tensor2.size())

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]) torch.float32 torch.Size([4, 2])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]) torch.Size([6, 2])


In [33]:
#tensor 运算 @ and matmul()
import torch
tensor = torch.arange(1,10,dtype = torch.float32).reshape(3,3)

res1 = tensor @ tensor.T
res2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(res1)
torch.matmul(tensor,tensor.T,out = y3)

print(res1)
print(res2)
print(y3)

#tensor 各元素对位相乘 * and mul()
z1 = res1 * res2
z2 = res1.mul(res2)
print(z1)
print(z2)

tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[  196.,  1024.,  2500.],
        [ 1024.,  5929., 14884.],
        [ 2500., 14884., 37636.]])
tensor([[  196.,  1024.,  2500.],
        [ 1024.,  5929., 14884.],
        [ 2500., 14884., 37636.]])


In [36]:
# torch 中tensor 类型变为原始python类型.item() 或 numpy类型.numpy()
import torch
import numpy
tensor = torch.arange(1,10,1,dtype = torch.float32).reshape(3,3)
sum = tensor.sum()
sum_item = sum.item()
print(sum_item,type(sum_item))

np_array = tensor.numpy()
print(np_array,np_array.dtype)

45.0 <class 'float'>
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float32


In [ ]:
# in_place 操作 一般不用 tensor.add_(1) 等价于 tensor += 5 tensor中每个元素加5
# 造成计算图路径混淆 不利于求导反向传播和模型训练

In [ ]:
# 计算图 深度学习框架都是用计算图来实现前向传播 反向传播 梯度下降的
#相当于一个模型参数等运算的流程图 路径
#Pytorch的计算图是动态计算图


In [38]:
# 用torchviz来可视化查看pytorch中运算的计算图
import torch
from torchviz import make_dot

#定义矩阵A 向量b x 常数c 
A = torch.randn(10,10,requires_grad = True) # True表示需要对A求导计算梯度
b = torch.randn(10,requires_grad = True)
c = torch.randn(1,requires_grad = True)
x = torch.randn(10,requires_grad = True)

#计算 x.T @ A + b.T @ x + c
res = torch.matmul(x.T, A) + torch.matmul(b,x) + c

# 生成计算图节点并可视化展示
dot = make_dot(res,params = {'A':A,'b':b,'c':c,'x':x})
dot.render('expression',format = 'png',cleanup= True,view = False)


C:\Users\22013\AppData\Local\Temp\ipykernel_8792\1518058132.py:12: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:3729.)
  res = torch.matmul(x.T, A) + torch.matmul(b,x) + c


'expression.png'